#!/bin/bash

#Compiles and runs the unit test and the cpp code properly and links it and stuff and does some other stuff so that I can actually run the unit test

qmake pa5_utest.pro && make clean && make && ./pa5_utest
