#!/bin/bash

#Compiles and runs the unit test and the cpp code properly and links it and stuff and does some other stuff so that I can actually run the unit test

g++ -Wall -std=c++20 pa4_main.cpp route.cpp ufo_thread.cpp ballistic.cpp ufo.cpp vertical.cpp ufosim.cpp -o main && ./main
